# Generated by Django 2.1.5 on 2019-02-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='studentID',
            field=models.CharField(help_text='学号，一般来说是十位（BIT）', max_length=10, verbose_name='student id'),
        ),
    ]
