# Generated by Django 2.1.5 on 2019-04-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='can_export',
            field=models.BooleanField(default=False, verbose_name='是否可以导出信息'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='can_schedule',
            field=models.BooleanField(default=False, verbose_name='是否可以安排面试'),
        ),
    ]
