# Generated by Django 2.1.5 on 2019-03-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': 'user information', 'verbose_name_plural': 'user information'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='real_name',
            new_name='realname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='studentID',
        ),
    ]
