# Generated by Django 2.2 on 2019-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190402_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='verifed',
            field=models.CharField(choices=[('unverified', '男'), ('failed', '女'), ('pass', '保密')], default='unverified', max_length=10, verbose_name='验证状态'),
        ),
    ]
