# Generated by Django 2.1.5 on 2019-03-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190306_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to='users.Club'),
        ),
    ]
