# Generated by Django 2.2 on 2019-04-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_club_verifed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='verifed',
            new_name='verified',
        ),
    ]
