# Generated by Django 2.2 on 2019-04-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190403_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='verified',
            field=models.CharField(choices=[('unverified', '验证中'), ('failed', '未通过'), ('pass', '通过')], default='unverified', max_length=10, verbose_name='验证状态'),
        ),
    ]
