# Generated by Django 2.2 on 2019-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190408_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='can_export',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='can_schedule',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为社团管理者'),
        ),
    ]
