# Generated by Django 2.2.4 on 2019-08-10 15:12

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190429_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='club',
            name='intro',
            field=models.TextField(blank=True, verbose_name='社团简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image', verbose_name='个性头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='intro',
            field=models.TextField(blank=True, help_text='用简短的话语介绍自己，可选。', verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='帮助社团联系到你', max_length=11, validators=[users.validators.validate_mobile], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='realname',
            field=models.CharField(max_length=50, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wechat_openID',
            field=models.CharField(blank=True, help_text='用于微信小程序登录', max_length=100, verbose_name='wechat openID'),
        ),
    ]
