# Generated by Django 2.2.4 on 2019-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190810_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileclub',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='自我介绍'),
        ),
    ]
