# Generated by Django 2.2.4 on 2019-08-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofileclub_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileclub',
            name='intro',
        ),
    ]
