# Generated by Django 2.2.6 on 2019-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofileclub_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/%Y-%m-%d', verbose_name='头像'),
        ),
    ]
