# Generated by Django 2.2.6 on 2019-11-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191029_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wechat_openID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='studentNumber',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='学号'),
        ),
    ]
