language: python
python:
  - "3.6"

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker build -t fkynjyq/interview_schedule.web:$TRAVIS_BRANCH ./schedule_backend

deploy:
  provider: script
  script: bash docker_push
