language: generic

services:
- docker

sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_62608a1c5d92_key -iv $encrypted_62608a1c5d92_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
 

install:
  - echo "install something"

  # missing test stage


script:
  - echo "test required."

before_deploy:
  - sudo apt-get install -y -qq yarn 
  - cd docs && yarn && yarn run docs:build && cd ..
  - docker build -t fkynjyq/interview_schedule.docs:$TRAVIS_BRANCH ./docs       
  - docker build -t fkynjyq/interview_schedule.web:$TRAVIS_BRANCH ./schedule_backend
  - bash docker_push.sh

deploy:
  provider: script
  on:
    branch: deploy
  script: ssh travis@59.110.233.235 "(cd interview-schedule && bash update_deploy.sh)"

stages:
  - name: before_deploy
    if: branch = deploy
  - name: deploy
    if: branch = deploy

addons:
  ssh_known_hosts: 59.110.233.235
