language: python

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker build -t fkynjyq/interview_schedule.web:$TRAVIS_BRANCH .

deploy:
  provider: script
  script: bash docker_push
