language: generic
branches:
  only:
  - master
services:
- docker
before_install:
  - openssl aes-256-cbc -K $encrypted_62608a1c5d92_key -iv $encrypted_62608a1c5d92_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - docker build -t fkynjyq/interview_schedule.web:$TRAVIS_BRANCH ./schedule_backend

deploy:
  provider: script
  script: bash docker_push.sh

after_success:
  - ssh travis@59.110.233.235 "bash interview-schedule/update_deploy.sh"

addons:
  ssh_known_hosts: 59.110.233.235