language: python

services:
  - docker

before_install:
  - docker build -t fkynjyq/interview_schedule.web:$TRAVIS_BRANCH .
  on:
    branch: master

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master