version: "2"
services:
  app:
    image: fkynjyq/interview_schedule.web:master
    restart: always
    ports:
      - 10101:80
  db:
    image: postgres
    restart: always
    environments:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: myapp