# Generated by Django 2.2 on 2019-04-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200, verbose_name='related link')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3')], max_length=20)),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='created time')),
            ],
        ),
    ]
