# Generated by Django 2.1.5 on 2019-02-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Interview Title')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('duration', models.IntegerField(verbose_name='duration( /minutes)')),
                ('interviewTimelines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.InterviewTimeline')),
            ],
        ),
    ]
