# Generated by Django 2.1.5 on 2019-04-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Interview Title')),
                ('description', models.TextField(max_length=600)),
                ('edit_finish', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, verbose_name="if it's public")),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeID', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('duration', models.IntegerField(verbose_name='duration( /minutes)')),
                ('passed', models.BooleanField(default=False, verbose_name='pass the interview')),
                ('interviewTimeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.InterviewTimeline')),
            ],
        ),
    ]
