# Generated by Django 2.1.5 on 2019-02-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timelines', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewtimeline',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.Interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Club'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='interviewtimeline',
            order_with_respect_to='interview',
        ),
        migrations.AlterOrderWithRespectTo(
            name='interview',
            order_with_respect_to='club',
        ),
    ]
