# Generated by Django 2.1.5 on 2019-04-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewtimeline',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterviewTimeline', to='timelines.Interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='users.Club'),
        ),
        migrations.AddField(
            model_name='interview',
            name='out_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Membership'),
        ),
        migrations.AddField(
            model_name='instate',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_state', to='timelines.Interview'),
        ),
        migrations.AddField(
            model_name='instate',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Membership'),
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('interviewTimeline', 'user')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='interviewtimeline',
            order_with_respect_to='interview',
        ),
        migrations.AlterOrderWithRespectTo(
            name='interview',
            order_with_respect_to='club',
        ),
        migrations.AlterUniqueTogether(
            name='instate',
            unique_together={('interview', 'membership')},
        ),
    ]
