# Generated by Django 2.1.5 on 2019-02-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_auto_20190210_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='interviewTimelines',
            new_name='interviewTimeline',
        ),
    ]
