# Generated by Django 2.1.5 on 2019-03-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_auto_20190316_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instate',
            old_name='Interview',
            new_name='interview',
        ),
    ]
