# Generated by Django 2.1.5 on 2019-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('timelines', '0004_auto_20190316_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instate',
            unique_together={('interview', 'membership')},
        ),
    ]
