# Generated by Django 2.2 on 2019-04-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_auto_20190408_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='out_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Membership'),
        ),
    ]
