# Generated by Django 2.2 on 2019-04-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_auto_20190410_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='comment',
            field=models.TextField(default='', max_length=200, verbose_name='comment'),
        ),
    ]
