# Generated by Django 2.1.5 on 2019-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_interview_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='edit_finish',
            field=models.BooleanField(default=False),
        ),
    ]
