# Generated by Django 2.2.4 on 2019-08-10 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_timeline_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtimeline',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeline',
            name='startTime',
            field=models.TimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='timeID',
            field=models.IntegerField(default=0, help_text='用于帮助区分统一时间段的不同时间片', verbose_name='时间ID'),
        ),
    ]
