# Generated by Django 2.1.5 on 2019-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0007_interview_edit_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='pass the interview'),
        ),
    ]
