# Generated by Django 2.2.4 on 2019-08-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0008_auto_20190811_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='out_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Membership'),
        ),
        migrations.AlterField(
            model_name='interviewtimeline',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewTimeline', to='timelines.Interview'),
        ),
        migrations.AlterField(
            model_name='interviewtimeline',
            name='remarks',
            field=models.TextField(max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='interviewTimeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='timelines.InterviewTimeline'),
        ),
    ]
