# Generated by Django 2.1.5 on 2019-03-20 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0008_timeline_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='timeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('interviewTimeline', 'user', 'timeID')},
        ),
    ]
