# Generated by Django 2.1.5 on 2019-03-27 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0009_auto_20190320_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('interviewTimeline', 'user')},
        ),
    ]
