# Generated by Django 2.1.5 on 2019-03-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0010_auto_20190327_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='out_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Membership'),
        ),
    ]
