# Generated by Django 2.2.4 on 2019-08-24 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0010_auto_20190824_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline', to=settings.AUTH_USER_MODEL),
        ),
    ]
