# Generated by Django 2.2.4 on 2019-09-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0011_auto_20190824_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together=set(),
        ),
    ]
