# Generated by Django 2.2.4 on 2019-09-07 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0012_auto_20190907_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('interviewTimeline', 'user')},
        ),
    ]
