# Generated by Django 2.2.6 on 2019-10-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0013_auto_20190907_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='is_public',
            new_name='make_public',
        ),
    ]
