# Generated by Django 2.2.6 on 2019-10-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0014_auto_20191029_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='make_public',
            new_name='is_public',
        ),
    ]
