# Generated by Django 2.2.6 on 2019-11-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0015_auto_20191029_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewtimeline',
            name='endTime',
            field=models.TimeField(default='21:00', verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='interviewtimeline',
            name='startTime',
            field=models.TimeField(default='18:30', verbose_name='开始时间'),
        ),
    ]
